### ISSUE TITLE
help with the testing

### ISSUE THREAD

**Issue by Assassinkin** [gpgmailencrypt/gpgmailencrypt#4]
I running into issues when running tests as all of them fails;
what i did
download the tar from pypi
extract 
then 

> cd test
> python3.5 gmeunittests.py

**Comment by Assassinkin** [comment]
@gpgmailencrypt  Yeah: 

> assassinkin@NagatoPN:~/Documents/atom/gitstuff/gpgmailencrypt/tests€ sudo pip3 install pypdf2 beautifulsoup4 icalendar python-magic lxml requests  passlib bcrypt
Requirement already satisfied (use --upgrade to upgrade): pypdf2 in /usr/local/lib/python3.5/dist-packages
Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4 in /usr/lib/python3/dist-packages
Requirement already satisfied (use --upgrade to upgrade): icalendar in /usr/local/lib/python3.5/dist-packages
Requirement already satisfied (use --upgrade to upgrade): python-magic in /usr/local/lib/python3.5/dist-packages
Requirement already satisfied (use --upgrade to upgrade): lxml in /usr/lib/python3/dist-packages
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python3/dist-packages
Requirement already satisfied (use --upgrade to upgrade): passlib in /usr/local/lib/python3.5/dist-packages
Requirement already satisfied (use --upgrade to upgrade): bcrypt in /usr/local/lib/python3.5/dist-packages
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in /usr/local/lib/python3.5/dist-packages (from icalendar)
Requirement already satisfied (use --upgrade to upgrade): pytz in /usr/local/lib/python3.5/dist-packages (from icalendar)
Requirement already satisfied (use --upgrade to upgrade): cffi>=1.1 in /usr/local/lib/python3.5/dist-packages (from bcrypt)
Requirement already satisfied (use --upgrade to upgrade): six>=1.4.1 in /usr/lib/python3/dist-packages (from bcrypt)
Requirement already satisfied (use --upgrade to upgrade): pycparser in /usr/local/lib/python3.5/dist-packages (from cffi>=1.1->bcrypt)
You are using pip version 8.1.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by gpgmailencrypt** [comment]
Do you get any error message from the unit tests?
Try ./gmeunittests.py  -vbc

**Comment by Assassinkin** [comment]
Some tests pass as they have an ok label in front of them 
`test_isencrypted_msg (__main__.gpgtests) ... ok`

others fails : 
```test_sophosvirus (__main__.virustests) ... skipped 'virusscanner sophos not found'

======================================================================
ERROR: test_7zun7z (__main__.archivetests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./gmeunittests.py", line 1928, in test_7zun7z
    containerfile=self.containerfile)
  File "../gmeutils/_dbg.py", line 49, in wrapper
    result=func(*args,**kwargs)
  File "../gmeutils/archivemanagers.py", line 1152, in create_zipfile
    password)))
TypeError: sequence item 0: expected str instance, NoneType found

======================================================================
ERROR: test_7zuncompress (__main__.archivetests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./gmeunittests.py", line 1950, in test_7zuncompress
    self.assertTrue(try_uncompress("7z","source.txt",password="secret"))
  File "./gmeunittests.py", line 1854, in try_uncompress
    result,rfile=xz.uncompress_file(filename,password=password)
  File "../gmeutils/_dbg.py", line 49, in wrapper
    result=func(*args,**kwargs)
  File "../gmeutils/archivemanagers.py", line 1305, in uncompress_file
    password=password)
  File "../gmeutils/_dbg.py", line 49, in wrapper
    result=func(*args,**kwargs)
  File "../gmeutils/archivemanagers.py", line 1363, in unzip_file
    if self.is_encrypted(zipfile) and password==None:
  File "../gmeutils/archivemanagers.py", line 1327, in is_encrypted
    stderr=subprocess.PIPE )
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1474, in _execute_child
    executable = os.fsencode(executable)
  File "/usr/lib/python3.5/os.py", line 862, in fsencode
    raise TypeError("expect bytes or str, not %s" % type(filename).__name__)
TypeError: expect bytes or str, not NoneType

======================================================================
ERROR: test_zipunzip (__main__.archivetests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./gmeunittests.py", line 1898, in test_zipunzip
    containerfile=self.containerfile)
  File "../gmeutils/_dbg.py", line 49, in wrapper
    result=func(*args,**kwargs)
  File "../gmeutils/archivemanagers.py", line 1152, in create_zipfile
    password)))
TypeError: sequence item 0: expected str instance, NoneType found

======================================================================
ERROR: test_zip_attachments_one_container (__main__.gmetests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./gmeunittests.py", line 789, in test_zip_attachments_one_container
    "testaddress@gpgmailencry.pt")
  File "../gmeutils/_dbg.py", line 49, in wrapper
    result=func(*args,**kwargs)
  File "../gpgmailencrypt.py", line 1980, in zip_attachments_one_container
    result,zipfile=Zip.create_zipfile(tempdir)
  File "../gmeutils/_dbg.py", line 49, in wrapper
    result=func(*args,**kwargs)
  File "../gmeutils/archivemanagers.py", line 1179, in create_zipfile
    password)))
TypeError: sequence item 0: expected str instance, NoneType found

======================================================================
ERROR: test_zip_attachments_one_container_msg (__main__.gmetests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./gmeunittests.py", line 800, in test_zip_attachments_one_container_msg
    "testaddress@gpgmailencry.pt")
  File "../gmeutils/_dbg.py", line 49, in wrapper
    result=func(*args,**kwargs)
  File "../gpgmailencrypt.py", line 1980, in zip_attachments_one_container
    result,zipfile=Zip.create_zipfile(tempdir)
  File "../gmeutils/_dbg.py", line 49, in wrapper
    result=func(*args,**kwargs)
  File "../gmeutils/archivemanagers.py", line 1179, in create_zipfile
    password)))
TypeError: sequence item 0: expected str instance, NoneType found

======================================================================
ERROR: test_zipattachment (__main__.gmetests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./gmeunittests.py", line 771, in test_zipattachment
    res=self.gme.zip_attachments(mail)
  File "../gmeutils/_dbg.py", line 49, in wrapper
    result=func(*args,**kwargs)
  File "../gpgmailencrypt.py", line 1698, in zip_attachments
    containerfile=None)
  File "../gmeutils/_dbg.py", line 49, in wrapper
    result=func(*args,**kwargs)
  File "../gmeutils/archivemanagers.py", line 1179, in create_zipfile
    password)))
TypeError: sequence item 0: expected str instance, NoneType found

======================================================================
ERROR: test_zipattachment_msg (__main__.gmetests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./gmeunittests.py", line 778, in test_zipattachment_msg
    res=self.gme.zip_attachments(email.message_from_string(mail))
  File "../gmeutils/_dbg.py", line 49, in wrapper
    result=func(*args,**kwargs)
  File "../gpgmailencrypt.py", line 1698, in zip_attachments
    containerfile=None)
  File "../gmeutils/_dbg.py", line 49, in wrapper
    result=func(*args,**kwargs)
  File "../gmeutils/archivemanagers.py", line 1179, in create_zipfile
    password)))
TypeError: sequence item 0: expected str instance, NoneType found

======================================================================
FAIL: test_zip_attachments_one_container_noattachment_withpdfcontent_msg (__main__.gmetests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./gmeunittests.py", line 827, in test_zip_attachments_one_container_noattachment_withpdfcontent_msg
    self.assertTrue(".zip" in result.as_string())
AssertionError: False is not true

Stdout:
Message-ID: <55D748F3.4020400@from.com>
Date: Fri, 21 Aug 2015 17:51:15 +0200
From: test@from.com
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Thunderbird/31.8.0
MIME-Version: 1.0
To: testaddress@gpgmailencry.pt
Subject: testmail
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 7bit

test



======================================================================
FAIL: test_encryptgpginline_withpdfcontent_msg (__main__.gpgtests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./gmeunittests.py", line 1533, in test_encryptgpginline_withpdfcontent_msg
    self.assertTrue(".pdf" in result.as_string())
AssertionError: False is not true

Stdout:
Content-Type: multipart/mixed; boundary="===============8379065980134896855=="
MIME-Version: 1.0
Message-ID: <55D748F3.4020400@from.com>
Date: Fri, 21 Aug 2015 17:51:15 +0200
From: test@from.com
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Thunderbird/31.8.0
To: testaddress@gpgmailencry.pt
Subject: testmail
Content-Transfer-Encoding: 7bit

--===============8379065980134896855==
MIME-Version: 1.0
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 7bit

-----BEGIN PGP MESSAGE-----
Version: GnuPG v2
Comment: 'Encrypted by gpgmailencrypt version 3.4.2'

hQEMA0frgA6jyJ37AQgAipT/37HqeFusbsjYhDAhB//7YnID2Hd6mAA7d3hlVTyV
bttuvgglFSXNVUHXkQJ1ujJ51gw1y1nba/q42ig5/iPrwpFJOCdriChKNpkgrn9m
s2oeGcnRVQUM38R88pZjPGYoDBiNgZuB2D6vRQp0PT3Yjw4fLVGjUT+iHlDKxLco
ALKyosk4mFAENPkeEuvviFgPcjNSwKu3GPpDvSN3/RewHXTbdy42+srVr0DnDUjZ
UZ6EH5ZAENEN8D+jvAgjfri/waof6+bkeIHea7aDAz8oLTr8Su/n9JAjqRiUK7PC
R8K9iQtTZxrojhBfbzTnl/t8pGNBFmAuCyU0eY0vPNJIAQ5rKxNo3VhfJUt/PWqi
hE2K6DDpa5HxfDudV5PeOkY5rbYu9m48WtNaHEkvpFKC8xTGnZhnEW2yXv6bQJ9y
qRnhXAZHy6mW
=No+U
-----END PGP MESSAGE-----

--===============8379065980134896855==--


----------------------------------------------------------------------
Ran 173 tests in 35.637s

FAILED (failures=2, errors=7, skipped=29)```

**Comment by gpgmailencrypt** [comment]
Just tried it out on a newly installed Ubuntu 16.04. I can reproduce the error messages. The reason is, that 7z is not installed. I will have to make these tests conditional, as 7z is not compulsary (but usually very useful) for gpgmailencrypt.

**Comment by Assassinkin** [comment]
@gpgmailencrypt  Thanks alot, I ll try that out and get back to you.

**Comment by Assassinkin** [comment]
@gpgmailencrypt As you mentioned install 7zip fixed the most of the errors except for those 2 : 

```======================================================================
FAIL: test_zip_attachments_one_container_noattachment_withpdfcontent_msg (__main__.gmetests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./gmeunittests.py", line 827, in test_zip_attachments_one_container_noattachment_withpdfcontent_msg
    self.assertTrue(".zip" in result.as_string())
AssertionError: False is not true

Stdout:
Message-ID: <55D748F3.4020400@from.com>
Date: Fri, 21 Aug 2015 17:51:15 +0200
From: test@from.com
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Thunderbird/31.8.0
MIME-Version: 1.0
To: testaddress@gpgmailencry.pt
Subject: testmail
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 7bit

test



======================================================================
FAIL: test_encryptgpginline_withpdfcontent_msg (__main__.gpgtests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./gmeunittests.py", line 1533, in test_encryptgpginline_withpdfcontent_msg
    self.assertTrue(".pdf" in result.as_string())
AssertionError: False is not true

Stdout:
Content-Type: multipart/mixed; boundary="===============0539851317638962927=="
MIME-Version: 1.0
Message-ID: <55D748F3.4020400@from.com>
Date: Fri, 21 Aug 2015 17:51:15 +0200
From: test@from.com
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Thunderbird/31.8.0
To: testaddress@gpgmailencry.pt
Subject: testmail
Content-Transfer-Encoding: 7bit

```

**Comment by gpgmailencrypt** [comment]
Same reason, just with the pdf related parts

**Comment by Assassinkin** [comment]
Thanks for the help. Installing pdftk fixed the other 2 issues.
I though they were python packages. I think it would be better if they are put before `and the python3 modules` section in the documentation.
